import = ["/home/stone/.config/alacritty/themes/themes/dracula.toml"]

[font]
size = 13.75

[font.normal]
family = "Fantasque Sans Mono"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[window]
opacity = 0.92
