services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    network_mode: 'host'
    privileged: true
    volumes:
      - /media/files/home-assistant/config:/config
      - type: bind
        source: /run/dbus
        target: /run/dbus
        read_only: true
    restart: 'unless-stopped'
    environment:
      - TZ=America/Los_Angeles
