wallpaper {
    monitor=DP-1
    path = /media/share/linux/wallpapers
    fit_mode = contain
    timeout = 2520
    order = random
}

wallpaper {
    monitor=HDMI-A-1
    path = /media/share/linux/wallpapers
    fit_mode = contain
    timeout = 2520
    order = random
}

splash = false
