name: dashy
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - /media/files/dashy/config/conf.yml:/app/user-data/conf.yml
    restart: 'unless-stopped'
    ports:
      - "80:8080"
    develop:
      watch:
        - action: sync+restart
          path: /media/files/dashy/config/conf.yml
          target: /app/user-data/conf.yml
